application: fcm-catnip
version: alpha-1a
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1h"

#
# skip files
#

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.less$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.coffee$
- node_modules\/^(.*/)?


#
# scaling
#

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

#
# builtins
#

builtins:
- deferred: off
- appstats: off
- remote_api: off

#
# dependencies
#

libraries:
- name: endpoints
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: protorpc
  version: latest
- name: PyAMF
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: PIL
  version: latest
- name: lxml
  version: latest
- name: matplotlib
  version: latest
- name: MySQLdb
  version: latest
- name: numpy
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest
- name: yaml
  version: latest


#
# handlers
#

handlers:

- url: /assets/js
  static_dir: fatcatmap/assets/js

- url: /assets/ext
  static_dir: fatcatmap/assets/ext

- url: /assets/img
  static_dir: fatcatmap/assets/img

- url: /assets/style
  static_dir: fatcatmap/assets/style

- url: /.*
  script: dispatch.application
  login: admin
  auth_fail_action: redirect
