# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'CocoaSPDY', '~> 1.0.1'
pod 'msgpack', '~> 0.1.3'
pod 'KIFastQR', '~> 0.3.0'
pod 'SocketRocket', '~> 0.1.1'
pod 'iOS-WebP', '0.3'
